apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: customerdbvolume
  name: customerdbvolume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
